# Loads default set of integrations. Do not remove.
bluetooth:

default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
# Example configuration.yaml entry
geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: "past_month_all_earthquakes"
    radius: 100
    minimum_magnitude: 0.0
    latitude: !secret lat
    longitude: !secret long
homeassistant:
  # packages:
  packages: !include_dir_named packages
  media_dirs:
    media: "/media"
  customize_glob:
    scene.*adrift:
      entity_picture: /local/hue_scene_icons/adrift.png

    scene.*amber_bloom:
      entity_picture: /local/hue_scene_icons/amber_bloom.png

    scene.*amethyst_valley:
      entity_picture: /local/hue_scene_icons/amethyst_valley.png

    scene.*arctic_aurora:
      entity_picture: /local/hue_scene_icons/arctic_aurora.png

    scene.*autumn_gold:
      entity_picture: /local/hue_scene_icons/autumn_gold.png

    scene.*beginnings:
      entity_picture: /local/hue_scene_icons/beginnings.png

    scene.*blood_moon:
      entity_picture: /local/hue_scene_icons/blood_moon.png

    scene.*blossom:
      entity_picture: /local/hue_scene_icons/blossom.png

    scene.*blue_lagoon:
      entity_picture: /local/hue_scene_icons/blue_lagoon.png

    scene.*blue_planet:
      entity_picture: /local/hue_scene_icons/blue_planet.png

    scene.*bright:
      entity_picture: /local/hue_scene_icons/bright.png

    scene.*cancun:
      entity_picture: /local/hue_scene_icons/cancun.png

    scene.*chinatown:
      entity_picture: /local/hue_scene_icons/chinatown.png

    scene.*concentrate:
      entity_picture: /local/hue_scene_icons/concentrate.png

    scene.*cool_bright:
      entity_picture: /local/hue_scene_icons/cool_bright.png

    scene.*crocus:
      entity_picture: /local/hue_scene_icons/crocus.png

    scene.*dimmed:
      entity_picture: /local/hue_scene_icons/dimmed.png

    scene.*disturbia:
      entity_picture: /local/hue_scene_icons/disturbia.png

    scene.*dreamy_dusk:
      entity_picture: /local/hue_scene_icons/dreamy_dusk.png

    scene.*emerald_flutter:
      entity_picture: /local/hue_scene_icons/emerald_flutter.png

    scene.*emerald_isle:
      entity_picture: /local/hue_scene_icons/emerald_isle.png

    scene.*energize:
      entity_picture: /local/hue_scene_icons/energize.png

    scene.*fairfax:
      entity_picture: /local/hue_scene_icons/fairfax.png

    scene.*first_light:
      entity_picture: /local/hue_scene_icons/first_light.png

    scene.*forest_adventure:
      entity_picture: /local/hue_scene_icons/forest_adventure.png

    scene.*frosty_dawn:
      entity_picture: /local/hue_scene_icons/frosty_dawn.png

    scene.*galaxy:
      entity_picture: /local/hue_scene_icons/galaxy.png

    scene.*golden_pond:
      entity_picture: /local/hue_scene_icons/golden_pond.png

    scene.*hal:
      entity_picture: /local/hue_scene_icons/hal.png

    scene.*hazy_days:
      entity_picture: /local/hue_scene_icons/hazy_days.png

    scene.*honolulu:
      entity_picture: /local/hue_scene_icons/honolulu.png

    scene.*horizon:
      entity_picture: /local/hue_scene_icons/horizon.png

    scene.*ibiza:
      entity_picture: /local/hue_scene_icons/ibiza.png

    scene.*lake_mist:
      entity_picture: /local/hue_scene_icons/lake_mist.png

    scene.*lake_placid:
      entity_picture: /local/hue_scene_icons/lake_placid.png

    scene.*lily:
      entity_picture: /local/hue_scene_icons/lily.png

    scene.*magneto:
      entity_picture: /local/hue_scene_icons/magento.png

    scene.*majestic_morning:
      entity_picture: /local/hue_scene_icons/majestic_morning.png

    scene.*memento:
      entity_picture: /local/hue_scene_icons/memento.png

    scene.*meriete:
      entity_picture: /local/hue_scene_icons/meriete.png

    scene.*miami:
      entity_picture: /local/hue_scene_icons/miami.png

    scene.*midsummer_sun:
      entity_picture: /local/hue_scene_icons/midsummer_sun.png

    scene.*midwinter:
      entity_picture: /local/hue_scene_icons/midwinter.png

    scene.*misty_ridge:
      entity_picture: /local/hue_scene_icons/misty_ridge.png

    scene.*moonlight:
      entity_picture: /local/hue_scene_icons/moonlight.png

    scene.*motown:
      entity_picture: /local/hue_scene_icons/motown.png

    scene.*mountain_breeze:
      entity_picture: /local/hue_scene_icons/mountain_breeze.png

    scene.*narcissa:
      entity_picture: /local/hue_scene_icons/narcissa.png

    scene.*nebula:
      entity_picture: /local/hue_scene_icons/nebula.png

    scene.*nightlight:
      entity_picture: /local/hue_scene_icons/nightlight.png

    scene.*ocean_dawn:
      entity_picture: /local/hue_scene_icons/ocean_dawn.png

    scene.*orange_fields:
      entity_picture: /local/hue_scene_icons/orange_fields.png

    scene.*osaka:
      entity_picture: /local/hue_scene_icons/osaka.png

    scene.*painted_sky:
      entity_picture: /local/hue_scene_icons/painted_sky.png

    scene.*palm_beach:
      entity_picture: /local/hue_scene_icons/palm_beach.png

    scene.*pensive:
      entity_picture: /local/hue_scene_icons/pensive.png

    scene.*precious:
      entity_picture: /local/hue_scene_icons/precious.png

    scene.*read:
      entity_picture: /local/hue_scene_icons/read.png

    scene.*relax:
      entity_picture: /local/hue_scene_icons/relax.png

    scene.*resplendant:
      entity_picture: /local/hue_scene_icons/resplendant.png

    scene.*rest:
      entity_picture: /local/hue_scene_icons/rest.png

    scene.*rio:
      entity_picture: /local/hue_scene_icons/rio.png

    scene.*rolling_hills:
      entity_picture: /local/hue_scene_icons/rolling_hills.png

    scene.*ruby_glow:
      entity_picture: /local/hue_scene_icons/ruby_glow.png

    scene.*savanna_sunset:
      entity_picture: /local/hue_scene_icons/savanna_sunset.png

    scene.*scarlet_dream:
      entity_picture: /local/hue_scene_icons/scarlet_dream.png

    scene.*soho:
      entity_picture: /local/hue_scene_icons/soho.png

    scene.*spring_blossom:
      entity_picture: /local/hue_scene_icons/spring_blossom.png

    scene.*spring_lake:
      entity_picture: /local/hue_scene_icons/spring_lake.png

    scene.*starlight:
      entity_picture: /local/hue_scene_icons/starlight.png

    scene.*still_waters:
      entity_picture: /local/hue_scene_icons/still_waters.png

    scene.*sunday_morning:
      entity_picture: /local/hue_scene_icons/sunday_morning.png

    scene.*sundown:
      entity_picture: /local/hue_scene_icons/sundown.png

    scene.*sunflare:
      entity_picture: /local/hue_scene_icons/sunflare.png

    scene.*tokyo:
      entity_picture: /local/hue_scene_icons/tokyo.png

    scene.*tropical_twilight:
      entity_picture: /local/hue_scene_icons/tropical_twilight.png

    scene.*tyrell:
      entity_picture: /local/hue_scene_icons/tyrell.png

    scene.*valley_dawn:
      entity_picture: /local/hue_scene_icons/valley_dawn.png

    scene.*vapor_wave:
      entity_picture: /local/hue_scene_icons/vapor_wave.png

    scene.*warm_embrace:
      entity_picture: /local/hue_scene_icons/warm_embrace.png

    scene.*winter_beauty:
      entity_picture: /local/hue_scene_icons/winter_beauty.png

    scene.*winter_mountain:
      entity_picture: /local/hue_scene_icons/winter_mountain.png
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret server_address

media_extractor:
recorder:
  db_url: !secret db_url

automation: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
# climate: !include climate.yaml
media_player: !include media_players.yaml
input_boolean: !include input_booleans.yaml
input_datetime: !include input_datetimes.yaml
input_number: !include input_numbers.yaml
input_select: !include input_selects.yaml
template: !include templates.yaml

